[package]
name = "termsprite"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = "0.26"
image = "0.24.7"
thiserror = "1.0.50"

